// GENERATED by scripts/embed-clips.mjs — do not edit by hand.
export const CLIPS = [
  {
    "id": "brand",
    "name": "DeepSeek 品牌片头",
    "ext": ".mp4",
    "bytes": 2767349,
    "sha256": "35c223de443d3edc",
    "b64": 3689800
  },
  {
    "id": "cyberpunk",
    "name": "DeepSeek 赛博朋克片头",
    "ext": ".mp4",
    "bytes": 3252010,
    "sha256": "d9a341af45ac4a9d",
    "b64": 4336016
  }
]
