// GENERATED by scripts/embed-clips.mjs — do not edit by hand.
export const CLIPS = [
  {
    "id": "brand",
    "name": "DeepSeek 品牌片头",
    "ext": ".mp4",
    "bytes": 2767349,
    "sha256": "35c223de443d3edc",
    "b64": 3689800
  },
  {
    "id": "cyberpunk",
    "name": "DeepSeek 赛博朋克片头",
    "ext": ".mp4",
    "bytes": 3252010,
    "sha256": "d9a341af45ac4a9d",
    "b64": 4336016
  },
  {
    "id": "awakening",
    "name": "DeepSeek 数字角色苏醒",
    "ext": ".mp4",
    "bytes": 4064757,
    "sha256": "a6c7e2b29921c9dd",
    "b64": 5419676
  },
  {
    "id": "startup",
    "name": "DeepSeek 启动问题",
    "ext": ".mp4",
    "bytes": 11265706,
    "sha256": "bfbc1df979118e78",
    "b64": 15020944
  }
]
